name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  check-on-nix:
    name: "Check: ${{ matrix.check }}"
    runs-on: namespace-profile-pareto-linux
    strategy:
      fail-fast: false
      matrix:
        check:
          [
            pwd-manager,
            firewall,
            screenlock,
            screenlock-plasma5,
            secureboot,
            luks,
            zfs,
            help,
            xfce,
            trayicon,
            autologin,
          ]
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: ./.github/actions/devenv
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: chmod o+rx /home/runner
        name: Update /home/runner permissions so that Nix is happy

      - run: nix build .#checks.x86_64-linux.${{ matrix.check }} --print-build-logs
        env:
          NIX_PAGER: cat
